services:
  db:
    image: postgres:17
    volumes:
      - .volumes/db_data:/var/lib/postgresql/data
    env_file:
      - ./source/.env
    ports:
        - "5432:5432"
    restart: always
  web:
    build:
      context: .
      dockerfile: ./source/Dockerfile
    env_file:
      - ./source/.env
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./source:/app
    depends_on:
      - db
    command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8080"