# Generated by Django 5.2.3 on 2025-08-22 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_remove_article_tags_article_new_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='new_tags',
            new_name='tags',
        ),
    ]
